### ISSUE TITLE
I need a software link

### ISSUE THREAD

**Issue by Ikaberry202** [jcope/OpenSource#8]

**Comment by radnakis** [comment]
which kind of software you want___?

**Comment by radnakis** [comment]
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '50' is not a valid attribute name.
Error: Failed to execute 'setAttribute' on 'Element': '50' is not a valid attribute name.
    at setAttr (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:1103:26)
    at updateAttrs (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:1155:5)
    at updateElement (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:816:3)
    at updateNode (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:767:15)
    at updateNodes (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:653:11)
    at updateElement (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:818:4)
    at updateNode (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:767:15)
    at updateComponent (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:828:9)
    at updateNode (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:770:9)
    at updateNodes (https://ui.perfetto.dev/v30.0-c41a63743/frontend_bundle.js:653:11)

v30.0-c41a63743 c41a63743ea1d3f55b5a0f1db14eb520d0dc739a
UA: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

**Comment by radnakis** [comment]
https://ui.perfetto.dev/#!/?s=f3ae53f98775a4d0dbcc415422a291b1a9dbee3f29ee78758c53d82c0b49c14
